version: '2'
services:
  emby:
    image: emby/embyserver_arm64v8:latest
    container_name: emby
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/Filmes/Filmes:/data/movies
      - /media/Filmes/Séries:/data/series
    restart: unless-stopped